# Generated by Django 5.0.14 on 2025-06-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='dog name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='image')),
                ('description', models.CharField(max_length=1000, verbose_name='description')),
            ],
            options={
                'verbose_name': 'dish',
                'verbose_name_plural': 'dishes',
            },
        ),
    ]
