# Generated by Django 5.0.14 on 2025-06-25 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drinks/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'name',
                'verbose_name_plural': 'names',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='alco')),
                ('description', models.CharField(max_length=1000, verbose_name='description')),
            ],
            options={
                'verbose_name': 'alco',
                'verbose_name_plural': 'alcos',
            },
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.AddField(
            model_name='drink',
            name='alco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinks.type', verbose_name='alco'),
        ),
    ]
