# Generated by Django 5.0.14 on 2025-06-25 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_drink_type_delete_name_drink_alco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drink',
            options={'verbose_name': 'drink', 'verbose_name_plural': 'drinks'},
        ),
    ]
