# Generated by Django 5.0.14 on 2025-06-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_alter_drink_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drinks/', verbose_name='image'),
        ),
    ]
