# Generated by Django 5.0.14 on 2025-07-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(max_length=150, verbose_name='Содержимое'),
        ),
    ]
