# Generated by Django 5.0.14 on 2025-06-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_dish_drinkanddish_alter_drinkanddish_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkanddish',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
